### ISSUE TITLE
Incorrect json for axios crashes Paradise

### ISSUE THREAD

**Issue by Jbithell** [Paradise-Pi/ParadisePi#109]
![image](https://user-images.githubusercontent.com/8408967/187033867-88b127ed-a510-42f9-b769-5b3328f40803.jpeg)

**Comment by Jbithell** [comment]
[paradiselogs-1661609456376.txt](https://github.com/Paradise-Pi/ParadisePi/files/9438120/paradiselogs-1661609456376.txt)

**Comment by Jbithell** [comment]
```json
{"date":"Sat Aug 27 2022 15:03:29 GMT+0100 (British Summer Time)","error":{},"exception":true,"level":"error","message":"unhandledRejection: Unexpected token o in JSON at position 1\nSyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at /home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js:2:3598162\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)","os":{"loadavg":[0.43,0.37,0.36],"uptime":242125.78},"process":{"argv":["/home/pi/paradisepi/out/paradisepi-linux-arm64/paradisepi"],"cwd":"/home/pi","execPath":"/home/pi/paradisepi/out/paradisepi-linux-arm64/paradisepi","gid":1000,"memoryUsage":{"arrayBuffers":0,"external":3983952,"heapTotal":31764480,"heapUsed":23906500,"rss":155238400},"pid":1046,"uid":1000,"version":"v16.14.2"},"stack":"SyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at /home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js:2:3598162\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-08-27 15:03:29","trace":[{"column":null,"file":null,"function":"JSON.parse","line":null,"method":"parse","native":false},{"column":3598162,"file":"/home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js","function":null,"line":2,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":96,"method":"processTicksAndRejections","native":false}]}
{"date":"Sat Aug 27 2022 15:03:29 GMT+0100 (British Summer Time)","error":{},"exception":true,"level":"error","message":"unhandledRejection: Unexpected token o in JSON at position 1\nSyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at /home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js:2:3598162\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)","os":{"loadavg":[0.43,0.37,0.36],"uptime":242125.78},"process":{"argv":["/home/pi/paradisepi/out/paradisepi-linux-arm64/paradisepi"],"cwd":"/home/pi","execPath":"/home/pi/paradisepi/out/paradisepi-linux-arm64/paradisepi","gid":1000,"memoryUsage":{"arrayBuffers":0,"external":3983952,"heapTotal":31764480,"heapUsed":23906500,"rss":155238400},"pid":1046,"uid":1000,"version":"v16.14.2"},"stack":"SyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at /home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js:2:3598162\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-08-27 15:03:29","trace":[{"column":null,"file":null,"function":"JSON.parse","line":null,"method":"parse","native":false},{"column":3598162,"file":"/home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js","function":null,"line":2,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":96,"method":"processTicksAndRejections","native":false}]}
{"date":"Sat Aug 27 2022 15:03:29 GMT+0100 (British Summer Time)","error":{},"exception":true,"level":"error","message":"unhandledRejection: Unexpected token o in JSON at position 1\nSyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at /home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js:2:3598162\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)","os":{"loadavg":[0.43,0.37,0.36],"uptime":242125.78},"process":{"argv":["/home/pi/paradisepi/out/paradisepi-linux-arm64/paradisepi"],"cwd":"/home/pi","execPath":"/home/pi/paradisepi/out/paradisepi-linux-arm64/paradisepi","gid":1000,"memoryUsage":{"arrayBuffers":0,"external":3983952,"heapTotal":31764480,"heapUsed":23906500,"rss":155238400},"pid":1046,"uid":1000,"version":"v16.14.2"},"stack":"SyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at /home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js:2:3598162\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-08-27 15:03:29","trace":[{"column":null,"file":null,"function":"JSON.parse","line":null,"method":"parse","native":false},{"column":3598162,"file":"/home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js","function":null,"line":2,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":96,"method":"processTicksAndRejections","native":false}]}
{"address":"172.18.144.13","code":"ENETUNREACH","errno":-101,"level":"error","message":"send ENETUNREACH 172.18.144.13:10023","port":10023,"stack":"Error: send ENETUNREACH 172.18.144.13:10023\n    at doSend (node:dgram:705:16)\n    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)\n    at afterDns (node:dgram:651:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)","syscall":"send","timestamp":"2022-08-27 15:05:01"}
{"date":"Sat Aug 27 2022 15:06:57 GMT+0100 (British Summer Time)","error":{},"exception":true,"level":"error","message":"unhandledRejection: Unexpected token o in JSON at position 1\nSyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at /home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js:2:3598162\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)","os":{"loadavg":[0.68,0.52,0.21],"uptime":124.91},"process":{"argv":["/home/pi/paradisepi/out/paradisepi-linux-arm64/paradisepi"],"cwd":"/home/pi","execPath":"/home/pi/paradisepi/out/paradisepi-linux-arm64/paradisepi","gid":1000,"memoryUsage":{"arrayBuffers":0,"external":2346719,"heapTotal":25079808,"heapUsed":23433280,"rss":145035264},"pid":813,"uid":1000,"version":"v16.14.2"},"stack":"SyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at /home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js:2:3598162\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-08-27 15:06:57","trace":[{"column":null,"file":null,"function":"JSON.parse","line":null,"method":"parse","native":false},{"column":3598162,"file":"/home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js","function":null,"line":2,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":96,"method":"processTicksAndRejections","native":false}]}
{"date":"Sat Aug 27 2022 15:06:57 GMT+0100 (British Summer Time)","error":{},"exception":true,"level":"error","message":"unhandledRejection: Unexpected token o in JSON at position 1\nSyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at /home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js:2:3598162\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)","os":{"loadavg":[0.68,0.52,0.21],"uptime":124.91},"process":{"argv":["/home/pi/paradisepi/out/paradisepi-linux-arm64/paradisepi"],"cwd":"/home/pi","execPath":"/home/pi/paradisepi/out/paradisepi-linux-arm64/paradisepi","gid":1000,"memoryUsage":{"arrayBuffers":0,"external":2346719,"heapTotal":25079808,"heapUsed":23433280,"rss":145035264},"pid":813,"uid":1000,"version":"v16.14.2"},"stack":"SyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at /home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js:2:3598162\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-08-27 15:06:57","trace":[{"column":null,"file":null,"function":"JSON.parse","line":null,"method":"parse","native":false},{"column":3598162,"file":"/home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js","function":null,"line":2,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":96,"method":"processTicksAndRejections","native":false}]}
{"date":"Sat Aug 27 2022 15:06:57 GMT+0100 (British Summer Time)","error":{},"exception":true,"level":"error","message":"unhandledRejection: Unexpected token o in JSON at position 1\nSyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at /home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js:2:3598162\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)","os":{"loadavg":[0.68,0.52,0.21],"uptime":124.91},"process":{"argv":["/home/pi/paradisepi/out/paradisepi-linux-arm64/paradisepi"],"cwd":"/home/pi","execPath":"/home/pi/paradisepi/out/paradisepi-linux-arm64/paradisepi","gid":1000,"memoryUsage":{"arrayBuffers":0,"external":2346719,"heapTotal":25079808,"heapUsed":23433280,"rss":145035264},"pid":813,"uid":1000,"version":"v16.14.2"},"stack":"SyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at /home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js:2:3598162\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-08-27 15:06:57","trace":[{"column":null,"file":null,"function":"JSON.parse","line":null,"method":"parse","native":false},{"column":3598162,"file":"/home/pi/paradisepi/out/paradisepi-linux-arm64/resources/app/.webpack/main/index.js","function":null,"line":2,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":96,"method":"processTicksAndRejections","native":false}]}
{"address":"172.18.144.13","code":"ENETUNREACH","errno":-101,"level":"error","message":"send ENETUNREACH 172.18.144.13:10023","port":10023,"stack":"Error: send ENETUNREACH 172.18.144.13:10023\n    at doSend (node:dgram:705:16)\n    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)\n    at afterDns (node:dgram:651:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)","syscall":"send","timestamp":"2022-08-27 15:07:21"}
{"address":"172.18.144.13","code":"ENETUNREACH","errno":-101,"level":"error","message":"send ENETUNREACH 172.18.144.13:10023","port":10023,"stack":"Error: send ENETUNREACH 172.18.144.13:10023\n    at doSend (node:dgram:705:16)\n    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)\n    at afterDns (node:dgram:651:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)","syscall":"send","timestamp":"2022-08-27 15:07:21"}
```
